name: Auto Merge Ship PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto-merge:
    if: contains(github.event.pull_request.title, 'ship-') || contains(github.event.pull_request.title, 'ship -')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "${ADMIN_TOKEN}" | gh auth login --with-token

      - name: Check PR status and merge
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Verify all checks have passed
          ALL_CHECKS_PASSED=$(gh pr checks "$PR_NUMBER" --json state -q '.state == "COMPLETED"')

          if [ "$ALL_CHECKS_PASSED" = "true" ]; then
            echo "All checks have passed for PR #$PR_NUMBER. Verifying mergeable status..."
            
            # Check if PR is mergeable
            PR_MERGEABLE=$(gh pr view "$PR_NUMBER" --json mergeable -q '.mergeable')
            
            if [ "$PR_MERGEABLE" = "MERGEABLE" ]; then
              echo "PR #$PR_NUMBER is mergeable. Proceeding to merge..."
              gh pr merge "$PR_NUMBER" --merge --auto
              echo "PR #$PR_NUMBER merged successfully."
            else
              echo "PR #$PR_NUMBER is not mergeable. Skipping merge."
            fi
          else
            echo "Not all checks have passed for PR #$PR_NUMBER. Skipping merge."
          fi
