# .github/workflows/debug2.yml
name: Debug Python 3.1 EXACTO

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Buscar 3.1 EXACTO
      run: |
        echo "=== CONTENIDO EXACTO DE 3.1 ==="
        grep -n "3\.1" requirements.txt || echo "No en requirements"
        grep -n "3\.1" .github/workflows/codacy.yml || echo "No en codacy"
        grep -n "3\.1" docker/images/Dockerfile.prod || echo "No en docker prod"
        grep -n "3\.1" docker/images/Dockerfile.webhook || echo "No en docker webhook"
        grep -n "3\.1" docker/images/Dockerfile.dev || echo "No en docker dev"
        grep -n "3\.1" docker/images/Dockerfile.render || echo "No en docker render"
