name: Deploy to Render

on:
  # 1) Despliegue cuando un PR hacia main se cierra por merge
  pull_request:
    branches: [ main ]
    types: [ closed ]

  # 3) Despliegue cuando se crea (push) un tag
  push:
    tags:
      - 'v*'          # semver tipo v1.2.3
      - 'release-*'   # opcional: tags de release

jobs:
  # 2) Job de tests: debe pasar antes de desplegar
  test:
    # Ejecutar solo si:
    #  - es un PR cerrado por merge, o
    #  - es un push de tag
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Ajusta las herramientas según tu stack (Node, Python, Java, etc.)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test -- --ci

  deploy:
    needs: test
    # Igual que arriba: solo en PR mergeado o en push de tag
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
