name: Deploy to Render

on:
    push:
      branches:
        - main
    pull_request:
      types:
        - closed
      branches:
        - main


jobs:
###Parte añadida Lab 2 : - Permitir que se realice el despliegue solo si todas las pruebas han pasado
 test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      # Aquí instrucciones para pruebas del proyecto
      - name: Run tests
        run: |
          # Coloca aquí el comando para correr las pruebas de tu proyecto (por ejemplo, npm test, pytest, etc.)
          echo "Running tests..."
          # Simulando un paso de prueba exitosa
          exit 0

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Este paso solo se ejecutará si las pruebas pasan
    if: github.event.pull_request.merged == true  # Desplegar solo si el PR fue mergeado
   
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
          