name: Deploy to Render

on:
    push:
      branches:
        - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # Solo ejecutar si el push es resultado de un merge de PR
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
          coverage report --fail-under=1  # Falla si no hay al menos 1% de cobertura
        env:
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Este job solo se ejecuta si el job 'test' es exitoso
    # Solo ejecutar si el push es resultado de un merge de PR
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
